apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge2
spec:
  selector:
    matchLabels:
      run: challenge2
  replicas: 2
  template:
    metadata:
      labels:
        run: challenge2
        role: api
    spec:
      containers:
      - name: challenge2
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "200m" #200 millicpu (.2 cpu or 20% of the cpu)
