apiVersion: v1
kind: Service
metadata:
 name: service-challenge6-frontend
spec:
 ports:
 - port: 80
   protocol: TCP
   targetPort: 80
   nodePort: 30261
 selector:
   role: frontend
 type: LoadBalancer